---
title: "R Notebook"
output: html_notebook
---

```{r}
# install.packages("statnet")
# install.packages("ergm.count")
# install.packages("igraph")
# install.packages("network")
# install.packages("tergm")
# install.packages("ergm.multi")
```

```{r}
library(ergm)
library(network)
library(ergm.count)
library(statnet)
library(tergm)
```
```{r}
fit_weight19 <- ergm(net_topx ~ edges + mutual(form = "nabsdiff"),
                     response = "weight", 
                     reference = ~Geometric,
                     control = control.ergm(MCMC.samplesize = 2000,
                                            seed = 123))
summary(fit_weight19)
```
```{r}
fit_weight21 <- ergm(net_sib ~ edges + mutual(form = "nabsdiff"),
                     response = "weight", 
                     reference = ~Geometric,
                     control = control.ergm(MCMC.samplesize = 2000,
                                            seed = 123))
summary(fit_weight21)

```
```{r}
fit_weighted <- ergm(net_sib ~ edges + mutual, 
                    response = "weight", 
                    reference = ~Geometric, 
                    control = control.ergm(MCMC.interval = 10000,
                                           MCMC.samplesize = 20000,
                                           MCMC.burnin = 1000))
```

```{r}
fit_weight20 <- ergm(net_l_s ~ edges + mutual(form = "nabsdiff"),
                     response = "weight", 
                     reference = ~Geometric,
                     verbose = 5,
                     control = control.ergm(MCMC.burnin = 5000, 
                                            MCMC.samplesize = 5000,
                                            MCMC.interval = 10000, 
                                            MCMLE.maxit = 30,, 
                                            MCMLE.steplength = 0.2, 
                                            MCMLE.density.guard = 10,
                                            parallel = 12,
                                            seed = 123))
summary(fit_weight20)
```