---
title: "ERGM2"
author: "Maroan El Sirfy"
date: "2025-01-27"
output: html_document
---

```{r}
library(ergm)
library(igraph)
library(network)
library(intergraph)
library(ergm.count)
```


```{r}
g_simplified <- igraph::simplify(g_l, edge.attr.comb = list(weight = "sum"))
g_rebuilt <- igraph::graph_from_data_frame(igraph::as_data_frame(g_simplified, what = "edges"),
                                           vertices = igraph::as_data_frame(g_simplified, what = "vertices"),
                                           directed = igraph::is_directed(g_simplified))
net <- intergraph::asNetwork(g_rebuilt)
#net <- intergraph::asNetwork(sub_g_sf)


# Verify edge weights (replace "weight" with actual edge attribute name)
network::set.edge.attribute(net, "weight", igraph::get.edge.attribute(g_l, "weight"))

```


```{r}
#Check model formation worked as intended
summary(net)
network::list.edge.attributes(net)
```
```{r}
temp_n_weight <- network::get.edge.attribute(net, "weight")
typeof(temp_n_weight)
```

```{r}
fit_base <- ergm(net ~ edges)
summary(fit_base)
```

```{r}
fit_weights <- ergm(net ~ edges + edgecov(net, "weight"))
summary(fit_weights)
```

```{r}
gof_fit <- gof(fit_weights, control = control.gof.formula(nsim = 10), verbose = 4)
summary(gof_fit)
plot(gof_fit)
```
Okay this worked, at least there were no major errors, after I fixed your mistake.

```{r}
fit_weights2 <- ergm(net ~ edges + idegree(1:3) + odegree(1:3))
summary(fit_weights2)
```
```{r}
gof_fit2 <- gof(fit_weights2, control = control.gof.formula(nsim = 10), verbose = 4)
plot(gof_fit2)
```
```{r}
mcmc.diagnostics(fit_weights2)
```


```{r}
log_weights <- log1p(network::get.edge.attribute(net, "weight"))
network::set.edge.attribute(net, "log_weight", log_weights)
```

```{r}
fit_weights3 <- ergm(net ~ edges + edgecov(net, "log_weight"))
summary(fit_weights3)
```


```{r}
# Convert to adjacency matrix with weights
weight_matrix <- as.matrix(network::as.sociomatrix(net, attr = "weight"))

in_weights <- colSums(weight_matrix)  # Total borrowed per node
out_weights <- rowSums(weight_matrix) # Total lent per node

# Assign as nodal attributes in the network object
network::set.vertex.attribute(net, "in_weight", in_weights)
network::set.vertex.attribute(net, "out_weight", out_weights)

rm(weight_matrix)
```



```{r}
fit_weights4 <- ergm(net ~ edges + nodeicov("in_weight") + nodeocov("out_weight"))

summary(fit_weights4)
```


```{r}
fit_weights5 <- ergm(net ~ edges + nodeicov("in_weight") + nodeocov("out_weight") + 
     nodematch("in_weight") + nodematch("out_weight"))
summary(fit_weights5)
```

```{r}
fit_weights6 <- ergm(net ~ edges + nodeicov("in_weight") + nodeocov("out_weight") + idegree(1) + odegree(1))
summary(fit_weights6)
```

